import Header from "@/components/header";
import "./globals.css";
import { Source_Code_Pro } from "next/font/google";

const sourceSansPro = Source_Code_Pro({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={sourceSansPro.className}>{children}</body>
    </html>
  );
}
